// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: common/probe.proto

package probe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProbeRequest_NodeType int32

const (
	ProbeRequest_Coordinator ProbeRequest_NodeType = 0
	ProbeRequest_TaskWorker  ProbeRequest_NodeType = 1
	ProbeRequest_Connector   ProbeRequest_NodeType = 2
)

// Enum value maps for ProbeRequest_NodeType.
var (
	ProbeRequest_NodeType_name = map[int32]string{
		0: "Coordinator",
		1: "TaskWorker",
		2: "Connector",
	}
	ProbeRequest_NodeType_value = map[string]int32{
		"Coordinator": 0,
		"TaskWorker":  1,
		"Connector":   2,
	}
)

func (x ProbeRequest_NodeType) Enum() *ProbeRequest_NodeType {
	p := new(ProbeRequest_NodeType)
	*p = x
	return p
}

func (x ProbeRequest_NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProbeRequest_NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_probe_proto_enumTypes[0].Descriptor()
}

func (ProbeRequest_NodeType) Type() protoreflect.EnumType {
	return &file_common_probe_proto_enumTypes[0]
}

func (x ProbeRequest_NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProbeRequest_NodeType.Descriptor instead.
func (ProbeRequest_NodeType) EnumDescriptor() ([]byte, []int) {
	return file_common_probe_proto_rawDescGZIP(), []int{0, 0}
}

type ProbeRequest_ProbeType int32

const (
	ProbeRequest_Liveness  ProbeRequest_ProbeType = 0
	ProbeRequest_Readiness ProbeRequest_ProbeType = 1
)

// Enum value maps for ProbeRequest_ProbeType.
var (
	ProbeRequest_ProbeType_name = map[int32]string{
		0: "Liveness",
		1: "Readiness",
	}
	ProbeRequest_ProbeType_value = map[string]int32{
		"Liveness":  0,
		"Readiness": 1,
	}
)

func (x ProbeRequest_ProbeType) Enum() *ProbeRequest_ProbeType {
	p := new(ProbeRequest_ProbeType)
	*p = x
	return p
}

func (x ProbeRequest_ProbeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProbeRequest_ProbeType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_probe_proto_enumTypes[1].Descriptor()
}

func (ProbeRequest_ProbeType) Type() protoreflect.EnumType {
	return &file_common_probe_proto_enumTypes[1]
}

func (x ProbeRequest_ProbeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProbeRequest_ProbeType.Descriptor instead.
func (ProbeRequest_ProbeType) EnumDescriptor() ([]byte, []int) {
	return file_common_probe_proto_rawDescGZIP(), []int{0, 1}
}

type ProbeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeType  ProbeRequest_NodeType  `protobuf:"varint,1,opt,name=nodeType,proto3,enum=common.ProbeRequest_NodeType" json:"nodeType,omitempty"`
	ProbeType ProbeRequest_ProbeType `protobuf:"varint,2,opt,name=probeType,proto3,enum=common.ProbeRequest_ProbeType" json:"probeType,omitempty"`
}

func (x *ProbeRequest) Reset() {
	*x = ProbeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_probe_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeRequest) ProtoMessage() {}

func (x *ProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_probe_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeRequest.ProtoReflect.Descriptor instead.
func (*ProbeRequest) Descriptor() ([]byte, []int) {
	return file_common_probe_proto_rawDescGZIP(), []int{0}
}

func (x *ProbeRequest) GetNodeType() ProbeRequest_NodeType {
	if x != nil {
		return x.NodeType
	}
	return ProbeRequest_Coordinator
}

func (x *ProbeRequest) GetProbeType() ProbeRequest_ProbeType {
	if x != nil {
		return x.ProbeType
	}
	return ProbeRequest_Liveness
}

type ProbeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Memory    float32 `protobuf:"fixed32,1,opt,name=memory,proto3" json:"memory,omitempty"`
	Cpu       float32 `protobuf:"fixed32,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Available bool    `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
}

func (x *ProbeResponse) Reset() {
	*x = ProbeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_probe_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResponse) ProtoMessage() {}

func (x *ProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_probe_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResponse.ProtoReflect.Descriptor instead.
func (*ProbeResponse) Descriptor() ([]byte, []int) {
	return file_common_probe_proto_rawDescGZIP(), []int{1}
}

func (x *ProbeResponse) GetMemory() float32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *ProbeResponse) GetCpu() float32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *ProbeResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type EventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *EventRequest) Reset() {
	*x = EventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_probe_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequest) ProtoMessage() {}

func (x *EventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_probe_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequest.ProtoReflect.Descriptor instead.
func (*EventRequest) Descriptor() ([]byte, []int) {
	return file_common_probe_proto_rawDescGZIP(), []int{2}
}

func (x *EventRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_probe_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_probe_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_common_probe_proto_rawDescGZIP(), []int{3}
}

func (x *EventResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EventResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_common_probe_proto protoreflect.FileDescriptor

var file_common_probe_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0xed, 0x01, 0x0a,
	0x0c, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a,
	0x08, 0x6e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08,
	0x6e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x62,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x70, 0x72, 0x6f,
	0x62, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x3a, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f,
	0x72, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x61, 0x73, 0x6b, 0x57, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x10, 0x02, 0x22, 0x28, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0c, 0x0a, 0x08, 0x4c, 0x69, 0x76, 0x65, 0x6e, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0d, 0x0a,
	0x09, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x10, 0x01, 0x22, 0x57, 0x0a, 0x0d,
	0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x6d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x03, 0x63, 0x70, 0x75, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x22, 0x0a, 0x0c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x35, 0x0a, 0x0d, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x42, 0x1e, 0x5a, 0x1c, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x62, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_probe_proto_rawDescOnce sync.Once
	file_common_probe_proto_rawDescData = file_common_probe_proto_rawDesc
)

func file_common_probe_proto_rawDescGZIP() []byte {
	file_common_probe_proto_rawDescOnce.Do(func() {
		file_common_probe_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_probe_proto_rawDescData)
	})
	return file_common_probe_proto_rawDescData
}

var file_common_probe_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_probe_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_probe_proto_goTypes = []interface{}{
	(ProbeRequest_NodeType)(0),  // 0: common.ProbeRequest.NodeType
	(ProbeRequest_ProbeType)(0), // 1: common.ProbeRequest.ProbeType
	(*ProbeRequest)(nil),        // 2: common.ProbeRequest
	(*ProbeResponse)(nil),       // 3: common.ProbeResponse
	(*EventRequest)(nil),        // 4: common.EventRequest
	(*EventResponse)(nil),       // 5: common.EventResponse
}
var file_common_probe_proto_depIdxs = []int32{
	0, // 0: common.ProbeRequest.nodeType:type_name -> common.ProbeRequest.NodeType
	1, // 1: common.ProbeRequest.probeType:type_name -> common.ProbeRequest.ProbeType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_probe_proto_init() }
func file_common_probe_proto_init() {
	if File_common_probe_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_probe_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProbeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_probe_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProbeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_probe_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_probe_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_probe_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_probe_proto_goTypes,
		DependencyIndexes: file_common_probe_proto_depIdxs,
		EnumInfos:         file_common_probe_proto_enumTypes,
		MessageInfos:      file_common_probe_proto_msgTypes,
	}.Build()
	File_common_probe_proto = out.File
	file_common_probe_proto_rawDesc = nil
	file_common_probe_proto_goTypes = nil
	file_common_probe_proto_depIdxs = nil
}
